package types

import (
	"fmt"
	"go/types"
	"strings"
)

// ModuleRef is a minimal reference to the loaded module.
type ModuleRef struct {
	Path string
	Dir  string
	Main bool
}

// Package is a fully loaded Go package, containing everything Morph needs to know about it.
type Package struct {
	Name       string
	ImportPath string
	Dir        string
	Module     *ModuleRef
	Imports    []string
	Constants  map[string]ConstantDecl // constant name -> ConstantDecl
	Functions  map[string]FunctionDecl // function name -> FunctionDecl
	Types      map[string]TypeDecl     // type name -> TypeDecl
}

// AsRef returns this Package as a PackageRef.
func (p Package) AsRef() PackageRef {
	return PackageRef{
		Name:       p.Name,
		ImportPath: p.ImportPath,
		Dir:        p.Dir,
	}
}

// PackageRef is a minimal reference to a loaded Package.
type PackageRef struct {
	Name       string
	ImportPath string
	Dir        string // Not set for packages not loaded directly by the loader
}

func packageRefFromTypesPackage(pkg *types.Package) PackageRef {
	if pkg == nil {
		return PackageRef{}
	}
	return PackageRef{
		Name:       pkg.Name(),
		ImportPath: pkg.Path(),
	}
}

func packageRefFromObject(obj types.Object, fallbacks ...PackageRef) PackageRef {
	if len(fallbacks) > 1 {
		panic("types: too many fallback package refs for packageRefFromObject")
	}
	var fallback PackageRef
	if len(fallbacks) == 1 {
		fallback = fallbacks[0]
	}
	if pkg := obj.Pkg(); pkg != nil {
		return packageRefFromTypesPackage(pkg)
	}
	return fallback
}

// ConstantDecl represents a constant declaration in a Go package.
type ConstantDecl struct {
	Package    PackageRef
	Name       string
	Type       Type
	Value      string
	IsExported bool
}

// FunctionDecl represents a function declaration in a Go package. Its structure is very similar to
// Method, but we keep track of a couple of extra pieces of information such as the source file it's
// declared in, and whether it was generated by Morph (i.e. so we can exclude it from discovery).
type FunctionDecl struct {
	Package    PackageRef
	Name       string
	TypeParams []TypeParam
	Params     []Parameter
	Results    []Parameter
	IsExported bool
	IsVariadic bool

	SourceFile    string
	IsInMorphFile bool
}

// TypeDecl represents a type declaration in a Go package.
type TypeDecl struct {
	Name       string
	Package    PackageRef
	IsAlias    bool
	Type       Type
	Underlying Type
	Fields     map[string]Field
	Methods    map[string]Method
	Constants  map[string]ConstantDecl // For convenience when working with enums
}

// Field describes a struct field.
type Field struct {
	Name       string
	Tag        string
	Type       Type
	IsExported bool
	IsEmbedded bool
}

// Method describes a method declared against a type.
type Method struct {
	Owner      Type       // The named type the method is declared on
	Receiver   *Parameter // Can be nil, for example, for interface methods
	Name       string
	TypeParams []TypeParam
	Params     []Parameter
	Results    []Parameter
	IsExported bool
	IsVariadic bool
}

// OwnerType returns the named type the method is declared on.
func (m Method) OwnerType() (Type, bool) {
	if m.Owner.Name != "" {
		return m.Owner, true
	}

	if m.Receiver == nil {
		return Type{}, false
	}

	receiver := m.Receiver.Type
	if receiver.Kind == TypeKindPointer && receiver.Elem != nil {
		receiver = *receiver.Elem
	}

	if receiver.Kind != TypeKindNamed && receiver.Kind != TypeKindAlias {
		return Type{}, false
	}

	return receiver, true
}

// Parameter describes a function parameter, result, or method receiver.
type Parameter struct {
	Name string
	Type Type
}

// TypeKind identifies the shape of a Type node.
type TypeKind string

const (
	TypeKindInvalid   TypeKind = "invalid"
	TypeKindBasic     TypeKind = "basic"
	TypeKindNamed     TypeKind = "named"
	TypeKindAlias     TypeKind = "alias"
	TypeKindPointer   TypeKind = "pointer"
	TypeKindSlice     TypeKind = "slice"
	TypeKindArray     TypeKind = "array"
	TypeKindMap       TypeKind = "map"
	TypeKindStruct    TypeKind = "struct"
	TypeKindInterface TypeKind = "interface"
	TypeKindSignature TypeKind = "signature"
	TypeKindTypeParam TypeKind = "type_param"
	TypeKindChan      TypeKind = "chan"
)

// Type is a recursive representation of a Go type. Elements of Type can be walked to inspect more
// complex types (e.g. pointers, maps, slices, arrays, so on).
type Type struct {
	Kind       TypeKind
	Name       string
	String     string
	Package    PackageRef
	Len        int64 // For arrays
	ChanDir    types.ChanDir
	Elem       *Type
	Key        *Type
	Value      *Type
	Fields     map[string]Field
	Methods    map[string]Method
	TypeParams []TypeParam
	TypeArgs   []Type
	Params     []Parameter
	Results    []Parameter
	IsVariadic bool
}

// TypeParam describes a generic type parameter.
type TypeParam struct {
	Name       string
	Constraint Type
}

// PointerElem unwraps aliased types, and returns the type and whether it's a pointer.
func PointerElem(typ Type) (Type, bool) {
	typ = UnwrapAlias(typ)
	if typ.Kind != TypeKindPointer || typ.Elem == nil {
		return typ, false
	}
	return UnwrapAlias(*typ.Elem), true
}

// PointerTo unwraps aliased types, and returns a type representing a pointer to the given type.
func PointerTo(typ Type) Type {
	typ = UnwrapAlias(typ)
	return Type{
		Kind: TypeKindPointer,
		Elem: &typ,
	}
}

// TypeKey returns a string key that uniquely identifies a type, including its structure and type
// arguments. This is used for caching and comparison purposes.
//
// We can't just rely on the String field from TypeInfo, which is provided by go/types,
// because Morph may substitute type arguments or unwrap aliases after loading.
func TypeKey(t Type) string {
	t = UnwrapAlias(t)

	switch t.Kind {
	case TypeKindNamed, TypeKindAlias:
		name := t.Name
		if t.Package.ImportPath != "" {
			name = t.Package.ImportPath + "." + name
		}
		if len(t.TypeArgs) > 0 {
			args := make([]string, 0, len(t.TypeArgs))
			for _, arg := range t.TypeArgs {
				args = append(args, TypeKey(arg))
			}
			return name + "[" + strings.Join(args, ", ") + "]"
		}
	case TypeKindTypeParam:
		if t.Name != "" {
			return t.Name
		}
	}

	if t.String != "" {
		return t.String
	}

	switch t.Kind {
	case TypeKindPointer:
		if t.Elem != nil {
			return "*" + TypeKey(*t.Elem)
		}
	case TypeKindSlice:
		if t.Elem != nil {
			return "[]" + TypeKey(*t.Elem)
		}
	case TypeKindArray:
		if t.Elem != nil {
			return fmt.Sprintf("[%d]%s", t.Len, TypeKey(*t.Elem))
		}
	case TypeKindMap:
		if t.Key != nil && t.Value != nil {
			return fmt.Sprintf("map[%s]%s", TypeKey(*t.Key), TypeKey(*t.Value))
		}
	}

	if t.Package.ImportPath != "" && t.Name != "" {
		return t.Package.ImportPath + "." + t.Name
	}

	return t.Name
}

// Unwrap unwraps a chain of aliases and/or pointers (potentially interleaved) to return the
// underlying type at the end of the chain.
func Unwrap(typ Type) Type {
	typ = UnwrapAlias(typ)
	typ = UnwrapPointer(typ)

	if typ.Kind == TypeKindAlias || typ.Kind == TypeKindPointer {
		return Unwrap(typ)
	}

	return typ
}

// UnwrapAlias recursively unwraps a type alias to return the element it refers to.
func UnwrapAlias(typ Type) Type {
	if typ.Kind == TypeKindAlias && typ.Elem != nil {
		return UnwrapAlias(*typ.Elem)
	}
	return typ
}

// UnwrapPointer recursively unwraps pointer types to return the element it refers to.
func UnwrapPointer(typ Type) Type {
	if typ.Kind == TypeKindPointer && typ.Elem != nil {
		return UnwrapPointer(*typ.Elem)
	}
	return typ
}
