package types

import "go/types"

// ModuleRef is a minimal reference to the loaded module.
type ModuleRef struct {
	Path string
	Dir  string
	Main bool
}

// Package is a fully loaded Go package, containing everything Morph needs to know about it.
type Package struct {
	Name       string
	ImportPath string
	Dir        string
	Module     *ModuleRef
	Constants  map[string]ConstantDecl // constant name -> ConstantDecl
	Functions  map[string]FunctionDecl // function name -> FunctionDecl
	Types      map[string]TypeDecl     // type name -> TypeDecl
}

// AsRef returns this Package as a PackageRef.
func (p Package) AsRef() PackageRef {
	return PackageRef{
		Name:       p.Name,
		ImportPath: p.ImportPath,
		Dir:        p.Dir,
	}
}

// PackageRef is a minimal reference to a loaded Package.
type PackageRef struct {
	Name       string
	ImportPath string
	Dir        string // Not set for packages not loaded directly by the loader
}

func packageRefFromTypesPackage(pkg *types.Package) PackageRef {
	if pkg == nil {
		return PackageRef{}
	}
	return PackageRef{
		Name:       pkg.Name(),
		ImportPath: pkg.Path(),
	}
}

func packageRefFromObject(obj types.Object, fallbacks ...PackageRef) PackageRef {
	if len(fallbacks) > 1 {
		panic("types: too many fallback package refs for packageRefFromObject")
	}
	var fallback PackageRef
	if len(fallbacks) == 1 {
		fallback = fallbacks[0]
	}
	if pkg := obj.Pkg(); pkg != nil {
		return packageRefFromTypesPackage(pkg)
	}
	return fallback
}

// ConstantDecl represents a constant declaration in a Go package.
type ConstantDecl struct {
	Package    PackageRef
	Name       string
	Type       Type
	Value      string
	IsExported bool
}

// FunctionDecl represents a function declaration in a Go package. Its structure is very similar to
// Method, but we keep track of a couple of extra pieces of information such as the source file it's
// declared in, and whether it was generated by Morph (i.e. so we can exclude it from discovery).
type FunctionDecl struct {
	Package    PackageRef
	Name       string
	TypeParams []TypeParam
	Params     []Parameter
	Results    []Parameter
	IsExported bool
	IsVariadic bool

	SourceFile    string
	IsInMorphFile bool
}

// TypeDecl represents a type declaration in a Go package.
type TypeDecl struct {
	Name       string
	Package    PackageRef
	IsAlias    bool
	Type       Type
	Underlying Type
	Fields     map[string]Field
	Methods    map[string]Method
	Constants  map[string]ConstantDecl // For convenience when working with enums
}

// Field describes a struct field.
type Field struct {
	Name       string
	Tag        string
	Type       Type
	IsExported bool
	IsEmbedded bool
}

// Method describes a method declared against a type.
type Method struct {
	Receiver   *Parameter // Can be nil, for example, for interface methods
	Name       string
	TypeParams []TypeParam
	Params     []Parameter
	Results    []Parameter
	IsExported bool
	IsVariadic bool
}

// Parameter describes a function parameter, result, or method receiver.
type Parameter struct {
	Name string
	Type Type
}

// TypeKind identifies the shape of a Type node.
type TypeKind string

const (
	TypeKindInvalid   TypeKind = "invalid"
	TypeKindBasic     TypeKind = "basic"
	TypeKindNamed     TypeKind = "named"
	TypeKindAlias     TypeKind = "alias"
	TypeKindPointer   TypeKind = "pointer"
	TypeKindSlice     TypeKind = "slice"
	TypeKindArray     TypeKind = "array"
	TypeKindMap       TypeKind = "map"
	TypeKindStruct    TypeKind = "struct"
	TypeKindInterface TypeKind = "interface"
	TypeKindSignature TypeKind = "signature"
	TypeKindTypeParam TypeKind = "type_param"
	TypeKindChan      TypeKind = "chan"
)

// Type is a recursive representation of a Go type. Elements of Type can be walked to inspect more
// complex types (e.g. pointers, maps, slices, arrays, so on).
type Type struct {
	Kind       TypeKind
	Name       string
	String     string
	Package    PackageRef
	Len        int64 // For arrays
	ChanDir    types.ChanDir
	Elem       *Type
	Key        *Type
	Value      *Type
	Fields     map[string]Field
	Methods    map[string]Method
	TypeParams []TypeParam
	TypeArgs   []Type
	Params     []Parameter
	Results    []Parameter
	IsVariadic bool
}

// TypeParam describes a generic type parameter.
type TypeParam struct {
	Name       string
	Constraint Type
}

// UnwrapAlias recursively unwraps a type alias to return the element it refers to.
func UnwrapAlias(typ Type) Type {
	if typ.Kind == TypeKindAlias && typ.Elem != nil {
		return UnwrapAlias(*typ.Elem)
	}
	return typ
}
