// Code generated by morph; DO NOT EDIT.
package from

import (
	"github.com/seeruk/morph/lab/planner/to"
	"github.com/seeruk/morph/runtime/value"
)

func MapFromSingleToToSingle(source Single) to.Single {
	var target to.Single
	mapValue := func(source string) to.Stringy {
		return to.Stringy(source)
	}
	target.Bar = OtoO(source.Bar, mapValue)
	var baz []to.Optional[*to.Stringy]
	if source.Baz != nil {
		bazValues := *source.Baz
		var baz2 []to.Optional[*to.Stringy]
		if bazValues != nil {
			baz2 = make([]to.Optional[*to.Stringy], len(bazValues))
			for i, bazValue := range bazValues {
				mapValue2 := func(source string) *to.Stringy {
					targetValue := to.Stringy(source)
					var mapped *to.Stringy
					if targetValue != to.Stringy("") {
						mapped = &targetValue
					}
					return mapped
				}
				baz2[i] = OtoO(bazValue, mapValue2)
			}
		}
		baz = baz2
	}
	target.Baz = baz
	target.Bla = to.Stringy(source.Bla)
	target.Foo = source.Foo
	target.Nested = mapNestedFromNestedToToNested_r7kclcg54f_hk7klegxn7(source.Nested)
	return target
}

func MapToSingleFromFromSingle(source to.Single) Single {
	var target Single
	target.Bar = mapNestedToOptionalToFromOptional_r7kclcg54f_34cbwczf3y(source.Bar)
	bazValues := source.Baz
	var baz []Optional[string]
	if bazValues != nil {
		baz = make([]Optional[string], len(bazValues))
		for i, bazValue := range bazValues {
			baz[i] = mapNestedToOptionalToFromOptional_r7kclcg54f_bvp2wedpul(bazValue)
		}
	}
	bazValue2 := baz
	var baz2 *[]Optional[string]
	if bazValue2 != nil {
		baz2 = &bazValue2
	}
	target.Baz = baz2
	target.Bla = string(source.Bla)
	target.Foo = source.Foo
	target.Nested = mapNestedToNestedToFromNested_r7kclcg54f_3nru7fic2f(source.Nested)
	return target
}

func MapFromExplicitToToExplicit(source Explicit) to.Explicit {
	var target to.Explicit
	target.Foo = source.Foo.Unwrap()
	return target
}

func MapToExplicitFromFromExplicit(source to.Explicit) Explicit {
	var target Explicit
	fooValue := source.Foo
	target.Foo = OptionalOfString2(&fooValue)
	return target
}

func mapNestedFromNestedToToNested_r7kclcg54f_hk7klegxn7(source Nested) to.Nested {
	var target to.Nested
	target.Bar = int(source.Bar)
	var baz to.Optional[to.Stringy]
	if source.Baz != nil {
		mapValue := func(source string) to.Stringy {
			return to.Stringy(source)
		}
		baz = OtoO(*source.Baz, mapValue)
	}
	target.Baz = baz
	target.Foo = source.Foo.Unwrap()
	return target
}

func mapNestedToOptionalToFromOptional_r7kclcg54f_34cbwczf3y(source to.Optional[to.Stringy]) Optional[string] {
	var target Optional[string]
	target.Valid = source.Valid
	target.Value = string(source.Value)
	return target
}

func mapNestedToOptionalToFromOptional_r7kclcg54f_bvp2wedpul(source to.Optional[*to.Stringy]) Optional[string] {
	var target Optional[string]
	target.Valid = source.Valid
	var value2 string
	if source.Value != nil {
		value2 = string(*source.Value)
	}
	target.Value = value2
	return target
}

func mapNestedToNestedToFromNested_r7kclcg54f_3nru7fic2f(source to.Nested) Nested {
	var target Nested
	target.Bar = int64(source.Bar)
	bazValue := mapNestedToOptionalToFromOptional_r7kclcg54f_34cbwczf3y(source.Baz)
	var baz *Optional[string]
	if !value.IsComparableZero(bazValue) {
		baz = &bazValue
	}
	target.Baz = baz
	fooValue := source.Foo
	target.Foo = OptionalOfString(&fooValue)
	return target
}
