// Code generated by morph; DO NOT EDIT.
package mapping

import (
	"fmt"
	"github.com/seeruk/morph/lab/planner/from"
	"github.com/seeruk/morph/lab/planner/to"
	"github.com/seeruk/morph/runtime/value"
)

func MapFromRecipeToToRecipe(source *from.Recipe) to.Recipe {
	if source == nil {
		return to.Recipe{}
	}
	var target to.Recipe
	target.ID = to.RecipeID(source.RecipeId)
	target.Name = source.Name
	target.Servings = int(source.Servings)
	return target
}

func MapToRecipeFromFromRecipe(source to.Recipe) from.Recipe {
	var target from.Recipe
	target.Name = source.Name
	target.RecipeId = string(source.ID)
	target.Servings = int32(source.Servings)
	return target
}

func MapFromSingleToToSingle(source from.Single) to.Single {
	var target to.Single
	mapValue := func(source string) to.Stringy {
		return to.Stringy(source)
	}
	target.Bar = from.OtoO(source.Bar, mapValue)
	var baz []to.Optional[*to.Stringy]
	if source.Baz != nil {
		bazValues := *source.Baz
		var baz2 []to.Optional[*to.Stringy]
		if bazValues != nil {
			baz2 = make([]to.Optional[*to.Stringy], len(bazValues))
			for i, bazValue := range bazValues {
				mapValue2 := func(source string) *to.Stringy {
					targetValue := to.Stringy(source)
					var mapped *to.Stringy
					if targetValue != to.Stringy("") {
						mapped = &targetValue
					}
					return mapped
				}
				baz2[i] = from.OtoO(bazValue, mapValue2)
			}
		}
		baz = baz2
	}
	target.Baz = baz
	target.Bla = to.Stringy(source.Bla)
	target.Foo = source.Foo
	target.Nested = mapNestedFromNestedToToNested_r7kclcg54f_hk7klegxn7(source.Nested)
	return target
}

func MapToSingleFromFromSingle(source to.Single) from.Single {
	var target from.Single
	target.Bar = mapNestedToOptionalToFromOptional_r7kclcg54f_34cbwczf3y(source.Bar)
	bazValues := source.Baz
	var baz []from.Optional[string]
	if bazValues != nil {
		baz = make([]from.Optional[string], len(bazValues))
		for i, bazValue := range bazValues {
			baz[i] = mapNestedToOptionalToFromOptional_r7kclcg54f_bvp2wedpul(bazValue)
		}
	}
	bazValue2 := baz
	var baz2 *[]from.Optional[string]
	if bazValue2 != nil {
		baz2 = &bazValue2
	}
	target.Baz = baz2
	target.Bla = string(source.Bla)
	target.Foo = source.Foo
	target.Nested = mapNestedToNestedToFromNested_r7kclcg54f_3nru7fic2f(source.Nested)
	return target
}

func MapFromDifficultyToToRecipeDifficulty(source from.Difficulty) (to.RecipeDifficulty, error) {
	switch source {
	case from.DifficultyEasy:
		return to.RecipeDifficultyEasy, nil
	case from.DifficultyHard:
		return to.RecipeDifficultyHard, nil
	case from.DifficultyMedium:
		return to.RecipeDifficultyMedium, nil
	case from.DifficultyUltra:
		return to.RecipeDifficultyInsane, nil
	}
	return to.RecipeDifficulty(0), fmt.Errorf("morph: no enum mapping for %v", source)
}

func MapToRecipeDifficultyFromFromDifficulty(source to.RecipeDifficulty) (from.Difficulty, error) {
	switch source {
	case to.RecipeDifficultyEasy:
		return from.DifficultyEasy, nil
	case to.RecipeDifficultyHard:
		return from.DifficultyHard, nil
	case to.RecipeDifficultyInsane:
		return from.DifficultyUltra, nil
	case to.RecipeDifficultyMedium:
		return from.DifficultyMedium, nil
	}
	return from.Difficulty(0), fmt.Errorf("morph: no enum mapping for %v", source)
}

func mapNestedFromNestedToToNested_r7kclcg54f_hk7klegxn7(source from.Nested) to.Nested {
	var target to.Nested
	target.Bar = int(source.Bar)
	var baz to.Optional[to.Stringy]
	if source.Baz != nil {
		mapValue := func(source string) to.Stringy {
			return to.Stringy(source)
		}
		baz = from.OtoO(*source.Baz, mapValue)
	}
	target.Baz = baz
	target.Foo = source.Foo.Unwrap()
	return target
}

func mapNestedToOptionalToFromOptional_r7kclcg54f_34cbwczf3y(source to.Optional[to.Stringy]) from.Optional[string] {
	var target from.Optional[string]
	target.Valid = source.Valid
	target.Value = string(source.Value)
	return target
}

func mapNestedToOptionalToFromOptional_r7kclcg54f_bvp2wedpul(source to.Optional[*to.Stringy]) from.Optional[string] {
	var target from.Optional[string]
	target.Valid = source.Valid
	var value2 string
	if source.Value != nil {
		value2 = string(*source.Value)
	}
	target.Value = value2
	return target
}

func mapNestedToNestedToFromNested_r7kclcg54f_3nru7fic2f(source to.Nested) from.Nested {
	var target from.Nested
	target.Bar = int64(source.Bar)
	bazValue := mapNestedToOptionalToFromOptional_r7kclcg54f_34cbwczf3y(source.Baz)
	var baz *from.Optional[string]
	if !value.IsComparableZero(bazValue) {
		baz = &bazValue
	}
	target.Baz = baz
	fooValue := source.Foo
	target.Foo = from.OptionalOfString(&fooValue)
	return target
}
