package internal

// MorphFileHeader is the exact header Morph writes to generated Go files.
// TODO: Does this actually need to be separate with the new structure?
const MorphFileHeader = "// Code generated by morph; DO NOT EDIT."
